# Personal Information
user:
  name: "Mr_Onion"
  title: "Student"
  location: "Shanghai China"
  email: "yaoonion@gmail.com"
  bio: "A student, OIer, Web Developer"

# Social Media Links
social:
  github: "https://github.com/SuperUseryjh"
  twitter: "https://twitter.com/MrOnion0408"

# Featured Projects
projects:
  - title: "Blog"
    description: "My Blog"
    tags: ["Blog"]
    github: "https://github.com/mr-onion-blog/hexo_tmp"
    demo: "https://mr-onion-blog.fun"
    featured: true

# Skills Configuration
skills:
  technical:
    - name: "JavaScript"
      icon: "javascript"
      
    - name: "Python"
      icon: "python"
      
    - name: "Node.js"
      icon: "nodedotjs"
      
    - name: "Docker"
      icon: "docker"
      
    - name: "MongoDB"
      icon: "mongodb"
      
    - name: "Redis"
      icon: "redis"
      
    - name: "Git"
      icon: "git"
      
    - name: "GitHub"
      icon: "github"

  soft:
    - name: "Problem Solving"
      icon: "FiBox"
      description: "Analytical thinking and creative solutions"
      
    - name: "Team Leadership"
      icon: "FiUsers"
      description: "Guiding and empowering teams"
      
    - name: "Communication"
      icon: "FiMessageSquare"
      description: "Clear and effective collaboration"
      
    - name: "Project Management"
      icon: "FiTarget"
      description: "Delivering results on time"
      
    - name: "Time Management"
      icon: "FiClock"
      description: "Efficient task prioritization"
      
    - name: "Adaptability"
      icon: "FiAward"
      description: "Embracing change and learning"
      
    - name: "Agile Mindset"
      icon: "FiRefreshCw"
      description: "Iterative improvement focus"
      
    - name: "Growth Mindset"
      icon: "FiTrendingUp"
      description: "Continuous self-improvement"

# Site Configuration
site:
  fonts:
    default: "maple-mono"
    alternatives:
      - "system-ui"
      - "sans-serif"
    "maple-mono":
      src: 
        - path: "/fonts/maple-mono/MapleMonoRegular.woff2"
          format: "woff2"
      weight: "normal"
      style: "normal"
      display: "fallback"
  
  theme:
    gradients:
      light:
        from: "#4F46E5"  # indigo-600
        to: "#06B6D4"    # cyan-600
      dark:
        from: "#00DC82"  # green
        to: "#36E4DA"    # cyan
  background: "#000000"
  text: "#FFFFFF"
  
  meta:
    title: "Luoshen - Portfolio"
    description: "Welcome to my personal portfolio showcasing my work and skills in software development"
    keywords: "software engineer, web developer, full-stack developer, react developer"
    ogImage: "/og-image.png"
  
  features:
    darkMode: true
    animations: true
    contactForm: true
    newsletter: false
    blog: false
  
  navigation:
    - label: "Home"
      path: "/"
      
    - label: "Skills"
      path: "#skills"
      
    - label: "Projects"
      path: "#projects"
      
    - label: "Contact"
      path: "#contact"

# GitHub Snake Configuration
githubSnake:
  enabled: true
  username: "Mr_Onion"
