name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # every day at 00:00
  workflow_dispatch: # allows to run the workflow manually
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            public/github-snake.svg
            public/github-snake-dark.svg?palette=github-dark
            public/github-snake-light.svg?palette=github-light

      - name: Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/github-snake*.svg
          git commit -m "🐍 update contribution graph" || echo "no update"
          git push
